#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d eDP1 I II III IV V  
bspc monitor -d DP1 VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# GtkFileChooserDialog
bspc config external_rules_command ~/.config/bspwm/external_rules
